"use client";
import Head from "next/head";
import Button from "@mui/material/Button";
import { useState } from "react";

export default function Home() {
  const [username, setUserName] = useState("");
  const [password, setPassword] = useState("");
  const handleLoginAction = () => {
    console.log(username, password);
  };
  return (
    <>
      <Head>
        <title>Will get better</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <h1>Login</h1>
        <input
          onChange={(event) => {
            setUserName(event.target.value);
          }}
          style={{ margin: "3px" }}
          value={username}
          type="text"
        />
        <input
          onChange={(event) => {
            setPassword(event.target.value);
          }}
          style={{ margin: "3px" }}
          value={password}
          type="text"
        />
        <Button variant="contained" onClick={handleLoginAction}>
          Login
        </Button>
      </div>
    </>
  );
}
